# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dbafc18488c2e2b4835a61523989a8af761672a1973fbd5d6e8a27a6d5f2280a2eadbfdb498dacd50ed132edb8796a24ec99c75a47674b16c898c480a07205e

test:
  secret_key_base: f338e9f050e08f468cbc45ae99ebea68b3898bf1ee1cc74c94f7078b1043093487b8f34b2980fe596155996bbc5528a64ae8874c58e196bf2baf32b1d5e1a48f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
